# -*- coding: utf-8 -*-
"""SkulTagger.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16oqUWmHLuEqV0xqzTnuC5hGloNmZQUNa
"""

import pandas as pd
import json
from google.colab import drive
drive.mount('/drive')

import pandas as pd
import json
from google.colab import drive
drive.mount('/drive')

def match_inscription(inscription):
  with open('/drive/My Drive/Scrappers/inscriptions.json') as f:
    inscription_tags = json.load(f)
    try:
      return inscription_tags[inscription]
    except KeyError:
      return ''

def match_item(item):
  item = item.lower().split()
  tag = []
  with open("/drive/My Drive/Scrappers/items.json") as f:
    item_tags = json.load(f)
    for i,row in enumerate(item):
      for j,row2 in enumerate(item_tags):
        if (row2 in row):
          tag.append(item_tags[row2])
  return tag   

df = pd.read_csv('/drive/My Drive/Scrappers/results.csv')
df.columns = df.iloc[0] 
df = df.iloc[1:,:]
tags = []
for i,row in enumerate(df.values):
  tag = []
  inscription_1 = row[2]
  inscription_2 = row[3]
  effect = row[5]
  result = match_inscription(inscription_1)
  if (result != ''):
    tag.append(result)
  result = match_inscription(inscription_2)
  if (result != ''):
      tag.append(result)
  result = match_item(effect)
  if (result != []):
    tag = tag + result
  tags.append(tag)

df.insert(6,'tags',tags)
df.to_csv('/drive/My Drive/Scrappers/tagged_results.csv')